### ISSUE TITLE
click "example 1" -> update, repeat until the back button goes into soft lock

### ISSUE THREAD

**Issue by heidji** [ionicthemes/ionic4-starter-app#2]
try it out, it stops working after a while..

**Comment by srikanth4372** [comment]
Browser console has few warnings and HTTP operations are not working please advise.

Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

**Comment by djabif** [comment]
Please try the new updated version and let me know if you can reproduce it (I couldn't) and in that case please send me more details so I can reproduce it.  Thanks.

**Comment by heidji** [comment]
it's fixed now
