### ISSUE TITLE
Cordova not available on browser console

### ISSUE THREAD

**Issue by srikanth4372** [ionicthemes/ionic4-starter-app#3]
Browser console has few warnings and HTTP operations are not working please advise.

Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

**Comment by san40511** [comment]
Are you seriously think that is should work in web browser? SplashScreen.hide() it's native plugin method and it's shouldn't work in web browser. This is not the reason why you http calls is not working. Looks like you do something wrong inside your http service.

**Comment by srikanth4372** [comment]
There is nothing wrong in HTTP calls. I have just initiated the package and trying to invoke. 

If there is anything wrong in the HTTP call method, an error will be different but the errors I am getting is Cordova not available. Not sure if this is a problem something related to version conflict between packages. Ionic version 

![image](https://user-images.githubusercontent.com/21060692/52260313-b0a3ac00-2936-11e9-805d-825f32be3d32.png)

**Comment by san40511** [comment]
cordova will be available on mobile device  only. You should build app for iphone or android and then run app on device or simulator and then you will see that error "Cordova not available" will disappear. cordova namespace available only on device, you can't use cordova methods inside your desktop browser.

**Comment by san40511** [comment]
no. you can't get it in browser. You must run xcode or android studio emulator  to get access cordova methods

**Comment by srikanth4372** [comment]
Will follow the same and thanks for the advice. Good day!
