### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by AugusDogus** [ionicthemes/ionic4-starter-app#5]
It would be incredibly helpful to those learning ionic4 if you could make unit and e2e tests.

**Comment by kamleshwebtech** [comment]
Thank you "Dayana Jabif", you saved 2 days of my life. Thanks a lot :) :)

**Comment by djabif** [comment]
thanks @AugusDogus for the feedback.

**Comment by djabif** [comment]
@kamleshwebtech happy to help :)
